version: '3.10'

services:
  flask-app:
    container_name: backend-compose
    image: backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5010:5000"
    depends_on:
      - postgres

  postgres:
    container_name: postgres-compose
    image: postgres:12
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty123
      - POSTGRES_DB=pacmail
    volumes:
      - postgres-data:/var/lib/postgresql/data

  frontend:
    image: node:latest
    ports:
      - 8090:8080
    depends_on:
      - flask-app 

volumes:
  postgres-data: