name: CD

on: workflow_dispatch

jobs:
    
    build-push:
        name: Build Push Image to Docker
        runs-on: windows-latest

        steps:
            - name: Check Repository
              uses: actions/checkout@v2

            - name: Login Docker
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASS }}

            - name: Set up Docker
              uses: docker/setup-buildx-action@v2
              
            - name: Build and push image
              uses: docker/build-push-action@v4
              with:
                context: ./backend
                file: ./flask/dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/flask:${{ github.run_number }}/Flask:latest
                  
    deploy: 
        name: server deploy
        runs-on: self-hosted
        needs: build-push

        steps:
          - name : Pull latest images
            run: |
              docker pull ${{ secrets.DOCKER_USERNAME }}/Flask:latest
      
          - name: Stop and Remove Existing Containers and Networks
            run: |
              docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q)
              docker network prune -f

          - name: Create Network and Run containers
            run : |               
              sudo docker compose up -d
              
          - name: Remove unused data
            run: |
               docker system prune -af